### ISSUE TITLE
The quality of translation from Japnese to English

### ISSUE THREAD

**Issue by gvskalyan** [sugiyamath/ja-en_translation_experiments#1]
Hi,
Can you please share the BLEU scores of the experiments vs package used such as fairseq,  t2t w.r.to particular corpus.
Also can good translations be obtained without using ASPEC as train corpus.

**Comment by sugiyamath** [comment]
Hi, @gvskalyan . Thanks for the comment.

I uploaded ```blue_score.txt```
https://github.com/sugiyamath/ja-en_translation_experiments/blob/master/bleu_score.txt

I don't have WAT submission data, so I used ASPEC test data to calculate BLUE scores.
You can compare the evaluation results of ASPEC: http://lotus.kuee.kyoto-u.ac.jp/WAT/evaluation/list.php?t=2&o=4

This project is just about ASPEC experiments, but you can use other data if you have it. 

It seems listed some ja-en translation data:
http://www.phontron.com/japanese-translation-data.php
